[anonymous-telemetry]
enabled = false

[GLOBAL]
pants_version = "2.14.0"

backend_packages.add = [
  "pants.backend.python",
]

[source]
root_patterns = ["python", "notebooks"]

[python]
interpreter_constraints = [">=3.8,<3.10"]
enable_resolves = true

[python.resolves]
  dsl = "3rdparty/python/dsl.lock"
  dsl_test = "3rdparty/python/dsl_test.lock"
  spark_3_2_1 = "3rdparty/python/spark_3_2_1.lock"
  test = "3rdparty/python/test.lock"
  mono = "3rdparty/python/mono.lock"

[pytest]
  version = "pytest==7.0.1"
  extra_requirements.add = [
    "pytest-timeout",
  ]
  lockfile = "3rdparty/python/pytest.lock"

